name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      run: |
        git clone https://github.com/${{ github.repository }}.git .

    - name: Install Dependencies and Python Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-pip python3-dev

    - name: Install Buildozer and Cython
      run: |
        pip3 install --upgrade pip --break-system-packages
        pip3 install cython==0.29.36 buildozer --break-system-packages

    - name: Build APK with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: package-apk
        path: bin/*.apk
